import Dashboard from "./images/sidebar/Dashboard.svg"
import Orders from "./images/sidebar/Orders.svg"
import Users from "./images/sidebar/Users.svg"
import Contact from "./images/sidebar/Contact.svg"
import Payments from "./images/sidebar/Payments.svg"
import Tickets from "./images/sidebar/Tickets.svg"
import Top from "./images/sidebar/Top.svg"
import Settings from "./images/sidebar/Settings.svg"
import Logout from "./images/sidebar/Logout.svg"
import Box from "./images/chartbox/Box.png"
import Cart from "./images/chartbox/Cart.png"
import Coin from "./images/chartbox/Coin.png"
import Rotate from "./images/chartbox/Rotate.png"
import Up from "./images/chartbox/Up.svg"
import Down from "./images/chartbox/Down.svg"
import Cooper from "./images/users/Cooper.png"
import Corey from "./images/users/Corey.png"
import Jayden from "./images/users/Jayden.png"
import Marcus from "./images/users/Marcus.png"
import Phillip from "./images/users/Phillip.png"
import Download from "./images/users/Download.svg"

//SIDEBAR DATA
export const menu = [
      {
        id: 1,
        title: "Dashboard",
        url: "/",
        icon: Dashboard,
      },
      {
        id: 2,
        title: "Orders",
        url: "/orders",
        icon: Orders,
      },
      {
        id: 3,
        title: "Users",
        url: "/users",
        icon: Users,
      },
      {
        id: 4,
        title: "Contact",
        url: "/contact",
        icon: Contact,
      },
      {
        id: 5,
        title: "Payments",
        url: "/payments",
        icon: Payments,
      },
      {
        id: 6,
        title: "Tickets",
        url: "/tickets",
        icon: Tickets,
      },
];
export const menuFooter = [
      {
        id: 1,
        title: "Top",
        url: "/",
        icon: Top,
      },
      {
        id: 2,
        title: "Settings",
        url: "/",
        icon: Settings,
      },
      {
        id: 2,
        title: "Logout",
        url: "/",
        icon: Logout,
      },
];

//MAIN CONTAINER DATA
export const chartBoxOrder = {
  color: "rgba(52, 202, 165, 0.12)",
  textColor: "rgba(52, 202, 165, 1)",
  icon: Box,
  icon2: Up,
  title: "Total Order",
  number: "350",
  dataKey: "users",
  percentage: "35.5%",
  chartData: [
    { name: "Sun", users: 500 },
    { name: "Mon", users: 0 },
    { name: "Tue", users: 100 },
    { name: "Thu", users: 0 },
    { name: "Thu", users: 0 },
    { name: "Wed", users: 200 },
    { name: "Thu", users: 0 },
    { name: "Fri", users: 500 },
    { name: "Fri", users: 450 },
    { name: "Sun", users: 500 },
    { name: "Mon", users: 300 },
    { name: "Tue", users: 600 },
    { name: "Thu", users: 500 },
    { name: "Thu", users: 500 },
    { name: "Wed", users: 800 },
    { name: "Thu", users: 700 },
    { name: "Fri", users: 750 },
    { name: "Fri", users: 500 },
    { name: "Sun", users: 1000 },
    { name: "Mon", users: 500 },
    { name: "Tue", users: 400 },
    { name: "Thu", users: 300 },
    { name: "Thu", users: 200 },
    { name: "Wed", users: 300 },
    { name: "Thu", users: 280 },
    { name: "Fri", users: 500 },
    { name: "Fri", users: 500 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 900 },
    { name: "Fri", users: 200 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 1000 },
    { name: "Fri", users: 600 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 700 },
    { name: "Fri", users: 700 },
  ],
};
export const chartBoxRefund = {
  color: "rgba(237, 84, 78, 0.12)",
  textColor: "rgba(237, 84, 78, 1)",
  icon: Rotate,
  icon2: Down,
  title: "Total Refund",
  number: "270",
  dataKey: "users",
  percentage: "23.5%",
  chartData: [
    { name: "Fri", users: 700 },
    { name: "Fri", users: 700 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 600 },
    { name: "Fri", users: 1000 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 200 },
    { name: "Fri", users: 900 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 500 },
    { name: "Thu", users: 280 },
    { name: "Thu", users: 200 },
    { name: "Thu", users: 300 },
    { name: "Thu", users: 500 },
    { name: "Wed", users: 800 },
    { name: "Thu", users: 500 },
    { name: "Tue", users: 600 },
    { name: "Mon", users: 300 },
    { name: "Sun", users: 500 },
    { name: "Fri", users: 450 },
    { name: "Fri", users: 500 },
    { name: "Thu", users: 50 },
    { name: "Wed", users: 200 },
    { name: "Thu", users: 0 },
    { name: "Thu", users: 0 },
    { name: "Tue", users: 100 },
    { name: "Mon", users: 0 },
    { name: "Sun", users: 500 }
]

};
export const chartBoxSales = {
  color: "rgba(237, 84, 78, 0.12)",
  textColor: "rgba(237, 84, 78, 1)",
  icon: Cart,
  icon2: Down,
  title: "Average Sales",
  number: "1567",
  dataKey: "users",
  percentage: "23.5%",
  chartData: [
    { name: "Fri", users: 700 },
    { name: "Fri", users: 700 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 600 },
    { name: "Fri", users: 1000 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 200 },
    { name: "Fri", users: 900 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 500 },
    { name: "Thu", users: 280 },
    { name: "Thu", users: 200 },
    { name: "Thu", users: 300 },
    { name: "Thu", users: 500 },
    { name: "Wed", users: 800 },
    { name: "Thu", users: 500 },
    { name: "Tue", users: 600 },
    { name: "Mon", users: 300 },
    { name: "Sun", users: 500 },
    { name: "Fri", users: 450 },
    { name: "Fri", users: 500 },
    { name: "Thu", users: 0 },
    { name: "Wed", users: 200 },
    { name: "Thu", users: 0 },
    { name: "Thu", users: 0 },
    { name: "Tue", users: 100 },
    { name: "Mon", users: 0 },
    { name: "Sun", users: 500 }
]

};
export const chartBoxIncome = {
  color: "rgba(52, 202, 165, 0.12)",
  textColor: "rgba(52, 202, 165, 1)",
  icon: Coin,
  icon2: Up,
  title: "Total Income",
  number: "350",
  dataKey: "users",
  percentage: "23.5%",
  chartData: [
    { name: "Sun", users: 500 },
    { name: "Mon", users: 0 },
    { name: "Tue", users: 100 },
    { name: "Thu", users: 0 },
    { name: "Thu", users: 0 },
    { name: "Wed", users: 200 },
    { name: "Thu", users: 0 },
    { name: "Fri", users: 500 },
    { name: "Fri", users: 450 },
    { name: "Sun", users: 500 },
    { name: "Mon", users: 300 },
    { name: "Tue", users: 600 },
    { name: "Thu", users: 500 },
    { name: "Thu", users: 500 },
    { name: "Wed", users: 800 },
    { name: "Thu", users: 700 },
    { name: "Fri", users: 750 },
    { name: "Fri", users: 500 },
    { name: "Sun", users: 1000 },
    { name: "Mon", users: 500 },
    { name: "Tue", users: 400 },
    { name: "Thu", users: 300 },
    { name: "Thu", users: 200 },
    { name: "Wed", users: 300 },
    { name: "Thu", users: 280 },
    { name: "Fri", users: 500 },
    { name: "Fri", users: 500 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 900 },
    { name: "Fri", users: 200 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 300 },
    { name: "Fri", users: 1000 },
    { name: "Fri", users: 600 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 800 },
    { name: "Fri", users: 700 },
    { name: "Fri", users: 700 },
  ],
};


export const bigChartData = [
	{
		name: "Jan",
		weekly: 8.0,
		monthly: 26.0,
	},
	{
		name: "Feb",
		weekly: 19,
		monthly: 22,
	},
	{
		name: "Mar",
		weekly: 5,
		monthly: 40,
	},
	{
		name: "Apr",
		weekly: 28,
		monthly: 16,
	},
	{
		name: "May",
		weekly: 9,
		monthly: 36,
	},
	{
		name: "Jun",
		weekly: 41,
		monthly: 50,
	},
	{
		name: "Jul",
		weekly: 8,
		monthly: 60,
	},
	{
		name: "Aug",
		weekly: 20,
		monthly: 51,
	},
	{
		name: "Sep",
		weekly: 31,
		monthly: 15,
	},
	{
		name: "Oct",
		weekly: 4,
		monthly: 55,
	},
	{
		name: "Nov",
		weekly: 30,
		monthly: 10,
	},
	{
		name: "Dec",
		weekly: 25,
		monthly: 30,
	},
];

export const userRows = [
  {
    id: 1,
    img: Marcus,
	icon: Download,
    name: "Marcus Bergson",
    date: "Nov 15, 2023",
    amount: "$80,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
	id: 2,
    img: Jayden,
	icon: Download,
    name: "Jaydon Vaccaro",
    date: "Nov 15, 2023",
    amount: "$150,000",
    status: "Refund",
    textColor: "rgba(237, 84, 78, 1)",
    invoice: "view",
  },
  {
    id: 3,
    img: Corey,
	icon: Download,
    name: "Corey Schleifer",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
	id: 4,
    img: Cooper,
	icon: Download,
    name: "Cooper Press",
    date: "Nov 14, 2023",
    amount: "$100,000",
    status: "Refund",
    textColor: "rgba(237, 84, 78, 1)",
    invoice: "view",
  },
  {
    id: 5,
    img: Phillip,
	icon: Download,
    name: "Phillip Lubin",
    date: "Nov 13, 2023",
    amount: "$78,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
	icon: Download,
    name: "Corey Schleifer",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
	icon: Download,
    name: "Will Kelly",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
  	icon: Download,
    name: "Jay May",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
	icon: Download,
    name: "Corey Leen",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
 	icon: Download,
    name: "Corey Schleifer",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
	icon: Download,
    name: "Corey Schleifer",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
  {
    id: 13,
	img: Jayden,
	icon: Download,
    name: "Piper Cole",
    date: "Nov 14, 2023",
    amount: "$87,000",
    status: "Paid",
    textColor: "rgba(52, 202, 165, 1)",
    invoice: "view",
  },
];

export const topPlatformData = [
  {
    id: 1,
	title: "Book Bazaar",
	amount: "$2,500,000",
    color: "#6160DC",
	percent: 70,
	value: "+15%"
	},
	{
    id: 2,
	title: "Artisan Aisle",
	amount: "$1,800,000",
    color: "#54C5EB",
	percent: 55,
	value: "+10%"
  },
	{
    id: 3,
	title: "Toy Troop",
	amount: "$1,200,000",
    color: "#FFB74A",
	percent: 30,
	value: "+8%"
  },
	{
    id: 4,
	title: "XStore",
	amount: "$1,900,000",
    color: "#6160DC",
	percent: 30,
	value: "+8%"
  },
];
